Feature/feature service
egarciaprofile/proyecto-individual pull request #2
Opened 2024-04-11 08:39 UTC by egarciaprofile

2024-04-12 06:59 UTC, jmaguero-profile requested changes
Genial la implementación del BaseService genérico de la mano de las interfaces de cada Service.

Aprovecho para comentarte que los métodos de los servicios deben trabajar con DTO's. Toda interacción con base de datos es mediante las clases que implementan el @Entity, pero en el momento en el que salimos del repository lo ideal es trabajar con los DTO's a la hora de manipular cualquier información de los objetos devueltos por el repository. Incluso aunque no se manipulen devolvemos DTO's de cara a los futuros controllers. Te invito a que implementes la devolución de DTO's en los métodos de las clases **ServiceImpl**.

Si tienes cualquier duda estoy a tu disposición.

Buen trabajo! ^^

2024-04-12 06:59 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/repository/TicketerPerformerRepository.java
> +    List<TicketerEvent> findByNameContainingIgnoreCase(String name);
Sí lo que devuelve el método es un listado de TicketerEvent debería ir en su clase Repository correspondiente

2024-04-12 08:35 UTC, egarciaprofile commented on src/main/java/dev/estebangperez/ticket/repository/TicketerPerformerRepository.java
> +    List<TicketerEvent> findByNameContainingIgnoreCase(String name);
oops, puse TicketerEvent en vez de TicketerPerformer

2024-04-16 10:25 UTC, jmaguero-profile approved these changes

2024-04-16 10:27 UTC, merged