Feature/feature controllers
egarciaprofile/proyecto-individual pull request #4
Opened 2024-04-24 10:52 UTC by egarciaprofile

2024-04-25 08:45 UTC, jmaguero-profile requested changes
- Utiliza el mismo criterio de respuesta en todos los endpoints. Devuelve ResponseEntity en todos y no solo en algunos de ellos.
- Por otro lado echa un vistazo a los imports que no estás usando en los archivos .java

Buen trabajo Esteban!

2024-04-25 08:48 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/util/TicketerPerformerMapper.java
> +                //.concerts(TicketerConcertMapper.mapConcertsFromDtoToEntity(dto.getConcerts()))
Elimina este comentario si la implementación no es necesaria

2024-04-25 08:48 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/util/TicketerUserMapper.java
> +                //.tickets(TicketerTicketMapper.mapTicketsFromDtoToEntity(dto.getTickets()))
Elimina este comentario si la implementación no es necesaria

2024-04-25 08:48 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/util/TicketerVenueMapper.java
> +                //.events(TicketerEventMapper.mapEventsFromDtoToEntity(dto.getEvents()))
Elimina estos comentarios si la implementación no es necesaria

2024-04-25 08:48 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/util/TicketerZoneMapper.java
> +                //.seats(TicketerSeatMapper.mapSeatsFromDtoToEntity(dto.getSeats()))
Elimina este comentario si la implementación no es necesaria

2024-04-26 06:20 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/controller/impl/TicketerConcertController.java
>                  .collect(Collectors.toList());
Genial la implementación de Streams. Te comento como extra: desde Java 16 se permite la implementación de Stream.toList() teniendo en cuenta que el List resultante es inmutable por lo que en este caso podría ser implementado.

2024-04-26 06:21 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/controller/impl/TicketerUserController.java
>                  .collect(Collectors.toList());
Genial la implementación de Streams. Te comento como extra: desde Java 16 se permite la implementación de Stream.toList() teniendo en cuenta que el List resultante es inmutable por lo que en este caso podría ser implementado.

2024-04-26 06:29 UTC, jmaguero-profile requested changes

2024-04-26 06:29 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/model/domain/TicketerZone.java
> -    private Set<TicketerSeat> seats;
¿Por qué eliminas la relación con Seats? ¿Ha cambiado el modelo entidad-relación?

2024-04-26 06:29 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/model/domain/TicketerVenue.java
> -    private Set<TicketerZone> zones;
¿Por qué eliminas la relación con zones y events? ¿Ha cambiado el modelo entidad-relación?

2024-04-26 06:29 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/model/domain/TicketerUser.java
> -    private Set<TicketerTicket> tickets;
¿Por qué eliminas la relación con Tickets? ¿Ha cambiado el modelo entidad-relación?

2024-04-26 06:29 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/model/domain/TicketerSeat.java
> -    private TicketerTicket ticket;
¿Por qué eliminas la relación con Ticket? ¿Ha cambiado el modelo entidad-relación?

2024-04-26 06:29 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/model/domain/TicketerPerformer.java
> -    private Set<TicketerConcert> concerts;
¿Por qué eliminas la relación con Concert? ¿Ha cambiado el modelo entidad-relación?

2024-04-26 06:29 UTC, jmaguero-profile commented on src/main/java/dev/estebangperez/ticket/model/domain/TicketerEvent.java
> -    private Set<TicketerSeat> seats;
¿Por qué eliminas la relación con Seats y Concerts? ¿Ha cambiado el modelo entidad-relación?

2024-04-26 06:48 UTC, egarciaprofile commented on src/main/java/dev/estebangperez/ticket/model/domain/TicketerEvent.java
> -    private Set<TicketerSeat> seats;
La base de datos esta igual, solo he removido estas variables "ayuda" para simplificar la programacion cuando estoy tratando con un objeto con varias relaciones
Foto de la base de datos con esta rama:
![image](https://github.com/egarciaprofile/proyecto-individual/assets/163855158/9c17fa4e-ab8b-41be-8d72-09eae02ecf60)

2024-04-26 06:50 UTC, jmaguero-profile approved these changes

2024-04-26 06:50 UTC, merged